name: fws_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_ui_auth: ^3.0.0
  fl_chart: ^0.69.0
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  file_picker: ^10.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true

