// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4EQlu0gxgDLT-JX3W4SFh2yya2c0Oxd8',
    appId: '1:476401337046:web:422a920bf1538f102bbf77',
    messagingSenderId: '476401337046',
    projectId: 'fws-dashboard',
    authDomain: 'fws-dashboard.firebaseapp.com',
    storageBucket: 'fws-dashboard.firebasestorage.app',
    measurementId: 'G-22KW141NPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRF9cKNZlbnobQRBUtxJo-67VlzuWxp30',
    appId: '1:476401337046:android:26504ac0f4f556692bbf77',
    messagingSenderId: '476401337046',
    projectId: 'fws-dashboard',
    storageBucket: 'fws-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4EQlu0gxgDLT-JX3W4SFh2yya2c0Oxd8',
    appId: '1:476401337046:web:a43c2ea419e0b6422bbf77',
    messagingSenderId: '476401337046',
    projectId: 'fws-dashboard',
    authDomain: 'fws-dashboard.firebaseapp.com',
    storageBucket: 'fws-dashboard.firebasestorage.app',
    measurementId: 'G-7V0174BM8X',
  );

}